### ISSUE TITLE
Unusual CPU Load 

### ISSUE THREAD

**Issue by roma0104** [flathub/org.godotengine.Godot#108]
With Godot 3.5 flatpak I have seen what I think is unusual CPU loads from Godot. 
Idle at the Project List I am seeing Godot usage of 5-6% on my laptop. 
I see this usage in both Linux Mint and Devuan, and regardless if I am using the AMD APU or my RTX 3060.

Where as using Linux Mint repo v3.2 and the official v3.5 static build, I see only a 0.15% usage.
I unfortunately don't know enough about Flatpak to go poking around for more information.

I shouldn't be resource-bound:
Mint 21 / Devuan Chimaera (Debian 11)
AMD Ryzen 9 5900HX w/ RTX 3060
32 GiB RAM

**Comment by Calinou** [comment]
Can you test [all official stable and beta/RC builds from 3.2 to 3.5](https://downloads.tuxfamily.org/godotengine/) to determine when the regression started? This is probably not a Flatpak-specific issue, but use official builds to confirm this.

**Comment by hammerandtongs** [comment]
This is also occurring on my 3+ flatpak installs on debian testing since 3.5 only.

No cpu load from the normal build

**Comment by roma0104** [comment]
Sorry for the delay on getting back to you on this. 

I didn't test all the builds between 3.2 and 3.5, mainly because I am NOT experiencing the problem in any of the official builds. I went back to 3.4 and I didn't experience any unusual CPU load. 

I then went and built the flatpak, commit by commit from 832b93bb02e2b31c0d8c6654ac29344d7f809fb8. I don't see the unusual uptick in load until the 3.5 commit: ea5b88353fcebc7cd95a9a729f756cd2f4888073
The commits following the 3.5 release still have the issue.

I also took a time to downgrade SCons back to 4.3 and 4.2 with the same results and picked-out the inclusion of a JRE. None of this seemed to result in a improved CPU load.

I agree in your issue mention that it seems to be a flatpak environment issue.

**Comment by Calinou** [comment]
If you have time, [set up a Flatpak development environment](https://docs.flatpak.org/en/latest/first-build.html), clone this repository and change the version here to use 3.5 betas and RCs: https://github.com/flathub/org.godotengine.Godot/blob/master/org.godotengine.Godot.yaml#L73-L75

You'll have to try each beta and RC one by one to determine when the regression started.

**Comment by kayomn** [comment]
This looks like it can be closed now as the referenced issue has been resolved.
