### ISSUE TITLE
Godot 4 support

### ISSUE THREAD

**Issue by xarses** [flathub/org.godotengine.Godot#111]
I cloned this today and started tweaking to try to build a godot-4.0-beta1 build. It looks like there should be some minor changes to the build yaml (if it finishes assembly this time). The process does have me wonder what form should the Godot 4 packaging take? I wonder if it would be best to run two lines for some time so folks can chose between either. I've no clue what the apatite is

**Comment by Calinou** [comment]
See https://github.com/flathub/org.godotengine.Godot/pull/109, which implicitly makes the `beta` branch use 4.0.beta instead of 3.6.beta.

**Comment by Zishan-Rahman** [comment]
[I think we can close this issue now :+1:](https://github.com/flathub/org.godotengine.Godot/commit/3c038ba71725efed2d62186e0ae6c1aa75e7acf2)
