### ISSUE TITLE
Popup windows are frequently hidden by default in GNOME Wayland

### ISSUE THREAD

**Issue by benkei-kuruma** [flathub/org.godotengine.Godot#129]
I am currently running Fedora 38 Silverblue on Wayland. 

Popup windows (e.g., Node creation) are frequently hidden by default. That is, they immediately "minimize", where I have to manually "unhide" them from the taskbar at the top. 

Note that I don't run any extensions besides the cute Fedora wallpaper logo the OS ships with. This is vanilla GNOME with Wayland.

Since it's easier to show than tell, here's a screencast of the issue.

[Screencast from 2023-07-23 12-45-09.webm](https://github.com/flathub/org.godotengine.Godot/assets/22654030/1e48cabc-4d96-4a6c-841f-f7528532e470)

As you can imagine, this is rather annoying as Godot IDE makes heavy use of these popup windows. 😅 I suppose if this is a Wayland issue I can switch to X11 when I'm running Godot, at least until it gets fixed.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/77333.

> I suppose if this is a Wayland issue I can switch to X11 when I'm running Godot, at least until it gets fixed.

Indeed, you need to switch to a X11 session.
