### ISSUE TITLE
Can't find adb and jarsigner binaries

### ISSUE THREAD

**Issue by Heryhelder** [flathub/org.godotengine.Godot#15]
Can't find adb and jarsigner in /usr/bin/ 

adb and jarsigner are needed to export for Android

Steps to reproduce:
Editor > Editor Settings > Export > Android > Adb > file and search for adb in /usr/bin/adb
and
Editor > Editor Settings > Export > Android > Jarsigner > file and search for jarsigner in /usr/bin/jarsigner

Expected results: find adb and jarsigner binaries in /usr/bin/

Downloading Godot binary from offical site i can find the binaries

Using Opensuse Leap 42.3 and Godot 3.0.2 via flatpak

**Comment by TingPing** [comment]
These will need to be built (maybe put in an extension).

**Comment by johannesgunnar** [comment]
Can confirm that I am also running into this issue on Ubuntu 18.04 with android sdk and adb installed from apt.

**Comment by rowbawts** [comment]
Is there a way to get this to work?

**Comment by davidholiday** [comment]
I am having the same problem on Ubuntu 18.04 - did *not* install via flatpak

**Comment by nexcode** [comment]
I think, need to rebuild the package and include these dependencies.

**Comment by Calinou** [comment]
@nexcode This requires both the jarsigner (which comes from OpenJDK 8) and ADB (which comes from the Android SDK command-line tools). Unfortunately, they both seem to be difficult to build from source. Perhaps we could use a pre-built binary for ADB, but I'm not sure if the license allows this – the Android SDK as a whole isn't under an open source license.

**Comment by nexcode** [comment]
Purely practically I can do. But I am not sure about the license.

**Comment by Raeryy** [comment]
I have installed Android Studio via Flatpak and I can successfully build a Android App...

But I'm having problems in make this work on Godot simple because I can't find the jarsigner.

Thanks to Android Studio, I located the ADB and debug key, but I simple can't find the jarsigner...

I tried install the openjdk flatpak extension, searched in all Android Studio folders, but I cant find.
Anyone know the location?

**Comment by ssokolow** [comment]
Just a note about the license for anyone who finds this via a search.

If anyone ever wants to try their hand at building Android SDK stuff from source to replace the wrappers and lock down the sandbox, the Android SDK's license prompted the Replicant project, which resulted in Debian having their own from-source builds of the Android SDK components to satisfy their rules for what licenses are allowed in their repository.

You could borrow build scripting from https://packages.debian.org/sid/adb and its dependencies.
