### ISSUE TITLE
Could not obtain an OpenGL 3.3 context!

### ISSUE THREAD

**Issue by ouck02** [flathub/org.godotengine.Godot#25]
Hello

This issue is the suite of my bad located issue: https://github.com/godotengine/godot/issues/23892
Because godot works great without flatpak.

My problem: I have OpenGL 4.5 but godot didn't start. I've updated my GPU driver to the last one, same error:

```
$ flatpak run org.godotengine.Godot
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: initialize: Could not obtain an OpenGL 3.3 context!
At: platform/x11/context_gl_x11.cpp:163.
ERROR: initialize: Error initializing GLAD
At: drivers/gles3/rasterizer_gles3.cpp:147.
ERROR: initialize: Your system's graphic drivers seem not to support OpenGL 3.3 / OpenGL ES 3.0, sorry :(
Try a drivers update, buy a new GPU or try software rendering on Linux; Godot will now crash with a segmentation fault.
At: drivers/gles3/rasterizer_gles3.cpp:157.
ERROR OS_Unix::execute - Could not create child process while executing: xmessage
OpenGL ES 3.0 Renderer:
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/libc.so.6() [0x35a1c32ff0] ()
-- END OF BACKTRACE --
/app/bin/godot: line 3: 4 Aborted (core dumped) /app/bin/godot-bin
```

Godot 3.0.6 (flatpak)
Linux Mint 19
AMD RX480
Driver AMDGPU-PRO 18.40.2.15
OpenGL ES profile version string: 4.5.13540 Compatibility Profile Context 18.40.2.15

**Comment by TingPing** [comment]
AMDGPU-PRO isn't supported by Flatpak at the moment. (And unless you require its OpenCL support you probably shouldn't be using it anyway.)

**Comment by ouck02** [comment]
Thank you, you're right: like explained here: https://amdgpu-install.readthedocs.io/en/latest/install-overview.html AMDGPU-PRO is for Radeon Pro GPU. Godot works with open source version !
