### ISSUE TITLE
Cannot use VS Code as external editor

### ISSUE THREAD

**Issue by knuxbbs** [flathub/org.godotengine.Godot#55]
This flatpack version of Godot cannot open Visual Studio Code as an external editor, [as indicated in the docs](https://docs.godotengine.org/en/3.2/getting_started/editor/external_editor.html).

I've tested with the Steam version, and this worked finely.

**Comment by Calinou** [comment]
I'm not sure if this can be implemented. Maybe it works if you set the external editor to a custom command that's basically `flatpak run <VS Code application ID>`?

**Comment by knuxbbs** [comment]
I'm using the official snap.
