### ISSUE TITLE
Support Godot Language Server Protocol TCP Socket

### ISSUE THREAD

**Issue by hammerandtongs** [flathub/org.godotengine.Godot#57]
https://github.com/godotengine/godot/pull/35864

It seems like the existing "--share=network" in the manifest covers this but just opened this to flag it?

**Comment by Calinou** [comment]
Have you tested it with an editor that only supports communication via TCP sockets?

**Comment by hammerandtongs** [comment]
Very happy to test!

On ubuntu 19.10 eoan -

1. Pulled this repository

1. Edited org.godotengine.Godot.yaml as suggested

1. sudo apt install flatpak-builder

1. git submodule init;git submodule update

1. flatpak install org.freedesktop.Sdk//19.08

1. sudo apt install scons

1. flatpak-builder --force-clean --user --install builddir org.godotengine.Godot.yaml

This fails unfortunately -

> Committing stage build-glu to cache
> ========================================================================
> Building module scons in /home/adam/tmp/org.godotengine.Godot/.flatpak-builder/build/scons-1
> ========================================================================
> Running: python3 setup.py install --prefix=/app
> python3: can't open file 'setup.py': [Errno 2] No such file or directory
> Error: module scons: Child process exited with code 2

**Comment by hammerandtongs** [comment]
Was not able to get that laptop building godot via flatpak-builder despite godot being able to build normally.

Moved to a different host and was able to build normally AND successfully test the lsp.

It mostly? seems to work for completion and doc on hover, not sure about all the extras but this seems to validate the manifest works well for godot+lsp.

I have some errors in the *Messages* buffer but I will explore the issue over at the lsp-mode github.

Thanks for the help and the flatpak in general!
