### ISSUE TITLE
Will not reopen

### ISSUE THREAD

**Issue by 5yk071cL3g10n** [flathub/org.godotengine.Godot#77]
Upon closing, GoDot will not open again.

**Comment by Calinou** [comment]
Can you try running `flatpak run org.godotengine.Godot` in a terminal and paste the terminal's output here?

Make sure you don't have a `project.godot` file in your `$HOME` folder. Otherwise, the project will try to run immediately without showing up the project manager.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/60332.
