### ISSUE TITLE
Fix the generated .desktop file

### ISSUE THREAD

**Issue by Brin-o** [flathub/org.godotengine.Godot#79]
The .desktop file that is generated when installing this flatpak is missing a `StartupWMClass` variable. This makes the programs icon blurry on certiant taskswitchers.

In my case I am on Elementary 5.1.7 and Plank (the dock) displays a blurry icon until I add `StartupWMClass=Godot_Engine` manually to the .desktop file. 

This is discussed in this open thread on the main godot page https://github.com/godotengine/godot/issues/20469

**Comment by Calinou** [comment]
As you linked, this is an upstream issue that should be fixed upstream: https://github.com/godotengine/godot/issues/20469
