### ISSUE TITLE
Build mono module

### ISSUE THREAD

**Issue by TingPing** [flathub/org.godotengine.Godot#8]
Build with `module_mono_enabled=yes`. This currently fails trying to find `monosgen-2` module.

**Comment by Bleuzen** [comment]
Any progress on this? Have you give it a try recently?

**Comment by ricvelozo** [comment]
@TingPing I managed to fix `monosgen-2` error. Now I'm stuck on the following NuGet error:

```console
scons: *** [bin/GodotSharp/Tools/GodotSharpTools.dll] /usr/lib/sdk/mono5/lib/nuget/nuget.exe: Exec format error
```

**Comment by ricvelozo** [comment]
@TingPing We cannot use `build-args` on Flathub (https://github.com/flathub/org.godotengine.Godot/pull/50#issuecomment-629912302)?

**Comment by TingPing** [comment]
@ricvelozo No, its unsafe.

**Comment by PureTryOut** [comment]
Has there been any progress on this?

**Comment by Calinou** [comment]
@PureTryOut Not that I know of.

**Comment by ricvelozo** [comment]
The glue code of Mono doesn't compile (#50) because of the Flatpak sandbox. A solution is use the official binaries, like flathub/org.blender.Blender@08eace8581653db6c95a974576d2e875fe1d7f42.

**Comment by xankz** [comment]
[Now that .NET 6 has been merged to the master branch,](https://github.com/godotengine/godot/pull/64089) is C# support for the flatpak version feasible?

**Comment by Calinou** [comment]
> [Now that .NET 6 has been merged to the master branch,](https://github.com/godotengine/godot/pull/64089) is C# support for the flatpak version feasible?

I haven't checked if this changes much with regards to packaging .NET 6 on Linux, but I wouldn't expect it to be a cakewalk still. Remember that Flatpaks aim to build everything from source (with the exception of the base platform), so using binary distributions is frowned upon (even if it's technically allowed).

**Comment by CharlieQLe** [comment]
I got a fork of this that has dotnet6 support via the `org.freedesktop.Sdk.Extension.dotnet6` SDK extension. I'm still working on it, but it doesn't seem to be too hard to complete. I'll submit a PR soon. If no huge problems come up, this should be ready by the first Godot 4 beta.

**Comment by CharlieQLe** [comment]
For anyone interested, PR #109 should have a working build of Godot 4 Alpha 15 with .NET 6 support. There are a few caveats however:
- The external mono editor does not work. However, using an external editor as in the README does work, as long as the editor has access to .NET 6.
- The Nuget packages needs to be accessible by the .NET 6 SDK extension. This can be done by running the following at the system level- not in a flatpak.
```
mkdir ~/MyLocalNugetSource
flatpak run --command=sh org.godotengine.Godot -c 'cp /app/bin/GodotSharp/Tools/nupkgs/* ~/MyLocalNugetSource/'
flatpak run --command=sh --runtime=org.freedesktop.Sdk//21.08 --filesystem=host org.freedesktop.Sdk.Extension.dotnet6//21.08 -c 'PATH="${PATH}:/usr/lib/sdk/dotnet6/bin" LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/sdk/dotnet6/lib" exec dotnet nuget add source ~/MyLocalNugetSource -n MyLocalNugetSource'
```
- Projects need to be restored. This can be done like so in the editor's integrated terminal:
```
dotnet restore
```

**Comment by Beryesa** [comment]
Are there any updates on this since now Godot's latest stable release uses dotnet instead of mono which seems to have better flatpak support?

**Comment by Calinou** [comment]
> Are there any updates on this since now Godot's latest stable release uses dotnet instead of mono which seems to have better flatpak support?

Please test https://github.com/flathub/org.godotengine.Godot/pull/109 (see its latest comments) and report back if it works correctly :slightly_smiling_face: 

Note that this will have to be a separate Flatpak, as C# support not only makes the Flatpak larger but also requires all projects exported with it to contain the .NET runtime (which makes your exported project larger). This is problematic for projects that only use GDScript.

**Comment by Zishan-Rahman** [comment]
Now that **both** [Godot 3's Mono version](https://flathub.org/apps/org.godotengine.Godot3Sharp) **and** [Godot 4's .NET version](https://flathub.org/apps/org.godotengine.GodotSharp) have their own Flatpaks on Flathub, I think this issue can be closed now :+1:

**Comment by Calinou** [comment]
Closing per the above comment. Thanks @Zishan-Rahman for their continued work on these Flatpaks :slightly_smiling_face:

**Comment by heliguy4599** [comment]
The Godot Base App Flatpak (https://github.com/flathub/org.godotengine.godot.BaseApp) still does not appear to support C#, despite its link to this issue. Have there been any developments regarding this? Thanks for the continued work!
